#!/usr/bin/env node
const fs       = require('fs')
const nunjucks = require('nunjucks')

const error = (message, code) => {
	console.error(message)
	process.exit(code || 1)
}

const [,, template, ...views] = process.argv

if (!template) error('Usage: nunjucks <template> [view]...')

/*
Handling views is TBD!
// Multiple views may be accepted. Merge all views together.
// Where conflicts arise, subsequent views override the previous ones.
const mergedView = views.reduce((merged, view) => {
	try {
		return { ...merged, ...JSON.parse(fs.readFileSync(view, 'utf8')) }
	} catch {
		error('Problem occurred handling view: ' + view)
	}
}, {})
*/

try {
	process.stdout.write(nunjucks.render(template, {}))
	process.exit(0)
} catch(e) {
	error(`${e.message}\nProblem occurred rendering template: ${template}`)
}
